{
 "title": "Drift Dashboard HW",
 "time": { "from": "2024-02-29T23:00:00.000Z", "to": "2024-03-31T21:59:59.000Z" },
 "panels": [
  {
   "title": "Fare Amount 0.5 Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", fare_amount_quantile05 FROM evidently_metrics_hw LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM evidently_metrics_hw LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM evidently_metrics_hw LIMIT 50 "
    }
   ]
  },
  {
   "title": "prediction drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM evidently_metrics_hw LIMIT 50 "
    }
   ]
  }
 ]
}